# syntax=docker/dockerfile:1
FROM golang:alpine AS build

ARG TARGETPLATFORM
ARG BUILDPLATFORM
ARG BUILDOS
ARG BUILDARCH
ARG BUILDVARIANT
ARG TARGETOS
ARG TARGETARCH

RUN echo "BUILDPLATFORM: $BUILDPLATFORM, TARGETPLATFORM: $TARGETPLATFORM, BUILDARCH: $BUILDARCH"

RUN echo "OS: $BUILDOS, ARCH: $BUILDARCH"

RUN echo "OS: $TARGETOS, ARCH: $TARGETARCH"

RUN echo "TEST"